[2025-04-09 00:15:22] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
2025-04-09 00:15:22,288 - discord.ext.commands.bot - WARNING - Privileged message content intent is missing, commands may not work as expected.
[2025-04-09 00:15:22] [INFO    ] discord.client: logging in using static token
2025-04-09 00:15:22,288 - discord.client - INFO - logging in using static token
2025-04-09 00:15:22,900 - bot - INFO - Help loaded!
2025-04-09 00:15:22,902 - bot - INFO - About loaded!
2025-04-09 00:15:22,906 - bot - INFO - AlarmSet loaded!
2025-04-09 00:15:22,908 - bot - INFO - BunRestaurant loaded!
2025-04-09 00:15:22,910 - bot - INFO - Other loaded!
2025-04-09 00:15:22,911 - bot - INFO - Ping loaded!
2025-04-09 00:15:22,913 - bot - INFO - ScheduleAlarmSet loaded!
[2025-04-09 00:15:23] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7848d992a8c35ebe12851baf976ab659).
2025-04-09 00:15:23,933 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 7848d992a8c35ebe12851baf976ab659).
2025-04-09 00:15:26,020 - bot - INFO - 금오공대 인공지능공학전공 알리미#7491 | V.1.0
[2025-04-09 00:15:26] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/discord/Kumoh-alarm/bot/__main__.py", line 62, in on_ready
    asyncio.create_task(globals()[module_name]())
                        ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_ce() missing 1 required positional argument: 'bot'
2025-04-09 00:15:26,021 - discord.client - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/discord/Kumoh-alarm/bot/__main__.py", line 62, in on_ready
    asyncio.create_task(globals()[module_name]())
                        ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_ce() missing 1 required positional argument: 'bot'
[2025-04-09 00:18:03] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
2025-04-09 00:18:03,736 - discord.ext.commands.bot - WARNING - Privileged message content intent is missing, commands may not work as expected.
[2025-04-09 00:18:03] [INFO    ] discord.client: logging in using static token
2025-04-09 00:18:03,736 - discord.client - INFO - logging in using static token
2025-04-09 00:18:04,384 - bot - INFO - Help loaded!
2025-04-09 00:18:04,386 - bot - INFO - About loaded!
2025-04-09 00:18:04,388 - bot - INFO - AlarmSet loaded!
2025-04-09 00:18:04,389 - bot - INFO - BunRestaurant loaded!
2025-04-09 00:18:04,391 - bot - INFO - Other loaded!
2025-04-09 00:18:04,392 - bot - INFO - Ping loaded!
2025-04-09 00:18:04,394 - bot - INFO - ScheduleAlarmSet loaded!
[2025-04-09 00:18:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 64f77d575cb1cdd298bc6e87d2e6f139).
2025-04-09 00:18:05,389 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 64f77d575cb1cdd298bc6e87d2e6f139).
2025-04-09 00:18:07,399 - bot - INFO - 금오공대 인공지능공학전공 알리미#7491 | V.1.0
[2025-04-09 00:18:43] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
2025-04-09 00:18:43,276 - discord.ext.commands.bot - WARNING - Privileged message content intent is missing, commands may not work as expected.
[2025-04-09 00:18:43] [INFO    ] discord.client: logging in using static token
2025-04-09 00:18:43,276 - discord.client - INFO - logging in using static token
2025-04-09 00:18:44,008 - bot - INFO - Help loaded!
2025-04-09 00:18:44,009 - bot - INFO - About loaded!
2025-04-09 00:18:44,011 - bot - INFO - AlarmSet loaded!
2025-04-09 00:18:44,013 - bot - INFO - BunRestaurant loaded!
2025-04-09 00:18:44,014 - bot - INFO - Other loaded!
2025-04-09 00:18:44,016 - bot - INFO - Ping loaded!
2025-04-09 00:18:44,018 - bot - INFO - ScheduleAlarmSet loaded!
[2025-04-09 00:18:45] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9ce7ab115ef235257f796fe45a6b9076).
2025-04-09 00:18:45,222 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 9ce7ab115ef235257f796fe45a6b9076).
2025-04-09 00:18:47,246 - bot - INFO - 금오공대 인공지능공학전공 알리미#7491 | V.1.0
[2025-04-09 00:18:54] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'alarmstatus'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/discord/Kumoh-alarm/bot/cogs/alarm_onoff.py", line 62, in alarmstatus
    if interaction.channel.id in all_table_dic[table]:
                                 ~~~~~~~~~~~~~^^^^^^^
KeyError: 'Academic_Information'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'alarmstatus' raised an exception: KeyError: 'Academic_Information'
2025-04-09 00:18:54,429 - discord.app_commands.tree - ERROR - Ignoring exception in command 'alarmstatus'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/discord/Kumoh-alarm/bot/cogs/alarm_onoff.py", line 62, in alarmstatus
    if interaction.channel.id in all_table_dic[table]:
                                 ~~~~~~~~~~~~~^^^^^^^
KeyError: 'Academic_Information'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'alarmstatus' raised an exception: KeyError: 'Academic_Information'
[2025-04-09 00:20:14] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'alarmstatus'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/discord/Kumoh-alarm/bot/cogs/alarm_onoff.py", line 62, in alarmstatus
    try:
         
KeyError: 'Hagsigdang'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'alarmstatus' raised an exception: KeyError: 'Hagsigdang'
2025-04-09 00:20:14,457 - discord.app_commands.tree - ERROR - Ignoring exception in command 'alarmstatus'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/discord/Kumoh-alarm/bot/cogs/alarm_onoff.py", line 62, in alarmstatus
    try:
         
KeyError: 'Hagsigdang'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'alarmstatus' raised an exception: KeyError: 'Hagsigdang'
[2025-04-09 00:22:52] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
2025-04-09 00:22:52,926 - discord.ext.commands.bot - WARNING - Privileged message content intent is missing, commands may not work as expected.
[2025-04-09 00:22:52] [INFO    ] discord.client: logging in using static token
2025-04-09 00:22:52,926 - discord.client - INFO - logging in using static token
2025-04-09 00:22:53,566 - bot - INFO - Help loaded!
2025-04-09 00:22:53,568 - bot - INFO - About loaded!
2025-04-09 00:22:53,573 - bot - INFO - AlarmSet loaded!
2025-04-09 00:22:53,574 - bot - INFO - BunRestaurant loaded!
2025-04-09 00:22:53,576 - bot - INFO - Other loaded!
2025-04-09 00:22:53,577 - bot - INFO - Ping loaded!
2025-04-09 00:22:53,579 - bot - INFO - ScheduleAlarmSet loaded!
[2025-04-09 00:22:54] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: acaef86387e0b96a3c30a36b1803222b).
2025-04-09 00:22:54,448 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: acaef86387e0b96a3c30a36b1803222b).
2025-04-09 00:22:56,462 - bot - INFO - 금오공대 인공지능공학전공 알리미#7491 | V.1.0
[2025-04-09 04:03:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
2025-04-09 04:03:17,733 - discord.gateway - INFO - Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
[2025-04-09 07:15:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
2025-04-09 07:15:15,101 - discord.gateway - INFO - Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
2025-04-09 09:31:43,416 - bot - INFO - Send msg : (11, 511102, 'https://www.kumoh.ac.kr/ko/sub06_01_01_02.do?mode=view&articleNo=511102&article.offset=0&articleLimit=10', '[교외행사]', '미국 해외취업(J-1인턴) 참가자 모집', '우상수')
[2025-04-09 09:36:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
2025-04-09 09:36:42,868 - discord.gateway - INFO - Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
2025-04-09 10:34:26,113 - bot - INFO - Send msg : (11, 511134, 'https://www.kumoh.ac.kr/ko/sub06_01_01_01.do?mode=view&articleNo=511134&article.offset=0&articleLimit=10', '[대학원]', '(장학) 2025학년도 1학기 대학원 스마일장학생 선발 및 장학금 지급 안내', '강선화')
[2025-04-09 10:44:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
2025-04-09 10:44:27,642 - discord.gateway - INFO - Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
[2025-04-09 12:15:49] [WARNING ] discord.gateway: WebSocket in shard ID None is ratelimited, waiting 29.97 seconds
2025-04-09 12:15:49,841 - discord.gateway - WARNING - WebSocket in shard ID None is ratelimited, waiting 29.97 seconds
[2025-04-09 12:15:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
2025-04-09 12:15:50,347 - discord.gateway - INFO - Shard ID None has successfully RESUMED session acaef86387e0b96a3c30a36b1803222b.
[2025-04-09 14:07:38] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
2025-04-09 14:07:38,058 - discord.ext.commands.bot - WARNING - Privileged message content intent is missing, commands may not work as expected.
[2025-04-09 14:07:38] [INFO    ] discord.client: logging in using static token
2025-04-09 14:07:38,058 - discord.client - INFO - logging in using static token
2025-04-09 14:07:38,692 - bot - INFO - Help loaded!
2025-04-09 14:07:38,694 - bot - INFO - About loaded!
2025-04-09 14:07:38,699 - bot - INFO - AlarmSet loaded!
2025-04-09 14:07:38,700 - bot - INFO - BunRestaurant loaded!
2025-04-09 14:07:38,702 - bot - INFO - Other loaded!
2025-04-09 14:07:38,704 - bot - INFO - Ping loaded!
2025-04-09 14:07:38,706 - bot - INFO - ScheduleAlarmSet loaded!
[2025-04-09 14:07:39] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5dbeb1dc353fc3cdc94a149be503d444).
2025-04-09 14:07:39,979 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 5dbeb1dc353fc3cdc94a149be503d444).
2025-04-09 14:07:41,995 - bot - INFO - 금오공대 인공지능공학전공 알리미#7491 | V.1.0
Traceback (most recent call last):
  File "/discord/Kumoh-alarm/bot/background/read_ce.py", line 18, in read_ce
    result = requests.get(ce_link, headers=header).text  # 해당 링크의 html 코드를 가져옴
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/discord/client.py", line 895, in runner
    await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.12/dist-packages/discord/client.py", line 824, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.12/dist-packages/discord/client.py", line 704, in connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.12/dist-packages/discord/gateway.py", line 623, in poll_event
    msg = await self.socket.receive(timeout=self._max_heartbeat_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/client_ws.py", line 334, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_websocket/reader_c.py", line 113, in read
  File "aiohttp/_websocket/reader_c.py", line 110, in aiohttp._websocket.reader_c.WebSocketDataQueue.read
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/discord/Kumoh-alarm/bot/background/read_kumoh.py", line 18, in read_kumoh
    result = await getText(link, header)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/discord/Kumoh-alarm/bot/utils/crawler.py", line 10, in getText
    async with session.get (url = url) as r :
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/client.py", line 1425, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/connector.py", line 1351, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/connector.py", line 995, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

Exception ignored in: <coroutine object read_kumoh at 0x7fb03058eae0>
Traceback (most recent call last):
  File "/discord/Kumoh-alarm/bot/background/read_kumoh.py", line 59, in read_kumoh
    await asyncio.sleep(60)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 659, in sleep
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
2025-04-09 14:07:42,544 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-12' coro=<read_kumoh() done, defined at /discord/Kumoh-alarm/bot/background/read_kumoh.py:10> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.12/asyncio/tasks.py:767]>
Traceback (most recent call last):
  File "/discord/Kumoh-alarm/bot/background/read_kumoh.py", line 18, in read_kumoh
    result = await getText(link, header)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit

Traceback (most recent call last):
  File "/discord/Kumoh-alarm/bot/background/read_kumoh.py", line 18, in read_kumoh
    result = await getText(link, header)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/discord/Kumoh-alarm/bot/utils/crawler.py", line 9, in getText
    async with aiohttp.ClientSession (connector=aiohttp.TCPConnector(verify_ssl=False), headers=header) as session:
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/connector.py", line 857, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/connector.py", line 262, in __init__
    loop = loop or asyncio.get_running_loop()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

[2025-04-09 14:07:46] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
2025-04-09 14:07:46,397 - discord.ext.commands.bot - WARNING - Privileged message content intent is missing, commands may not work as expected.
[2025-04-09 14:07:46] [INFO    ] discord.client: logging in using static token
2025-04-09 14:07:46,397 - discord.client - INFO - logging in using static token
2025-04-09 14:07:47,042 - bot - INFO - Help loaded!
2025-04-09 14:07:47,043 - bot - INFO - About loaded!
2025-04-09 14:07:47,045 - bot - INFO - AlarmSet loaded!
2025-04-09 14:07:47,047 - bot - INFO - BunRestaurant loaded!
2025-04-09 14:07:47,049 - bot - INFO - Other loaded!
2025-04-09 14:07:47,050 - bot - INFO - Ping loaded!
2025-04-09 14:07:47,052 - bot - INFO - ScheduleAlarmSet loaded!
[2025-04-09 14:08:39] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 758b6c58bd2e71e08d158d542548c5a7).
2025-04-09 14:08:39,886 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 758b6c58bd2e71e08d158d542548c5a7).
2025-04-09 14:08:41,900 - bot - INFO - 금오공대 인공지능공학전공 알리미#7491 | V.1.0
